# Generated by Django 2.0.3 on 2018-04-21 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BBS', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='tag',
        ),
    ]
