# Generated by Django 2.0.4 on 2018-05-07 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BBS', '0004_auto_20180507_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='contributor',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='BBS.User'),
            preserve_default=False,
        ),
    ]
