# Generated by Django 2.0.5 on 2018-06-07 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BBS', '0008_auto_20180519_1614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='goro',
        ),
        migrations.AddField(
            model_name='comment',
            name='commentary',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='contributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
